### ISSUE TITLE
General or Specific Packages for NeuroIO

### ISSUE THREAD

**Issue by alexmorley** [JuliaNeuro/julianeuro.github.io#10]
@rob-luke 
> Regarding reading neuro related file types (for example recordings from different machine types like EEG, MEG, etc) do we want a generic package for this? Or a package per file type?
> Something general like NeuroIO.jl or something specific per file type like NIRIO.jl for reading .nir files?

**Comment by alexmorley** [comment]
I think are advantages to both. Maybe for now it'd make sense to start with just NeuroIO but there might be merit to splitting things out later on if it get's too cumbersome?

**Comment by rob-luke** [comment]
Sounds good to me.  
Can you add me to the organization and ill set it up.

I will take some time to look at other established IO packages and see what the best approach is

**Comment by alexmorley** [comment]
Cool. And done.

**Comment by rob-luke** [comment]
Thanks

**Comment by rob-luke** [comment]
I just tried to assign this issue to myself but don't have high enough access in the organization.

**Comment by alexmorley** [comment]
now?

**Comment by rob-luke** [comment]
still can't

**Comment by alexmorley** [comment]
I think you need to accept the invitation?

https://github.com/JuliaNeuro/julianeuro.github.io/invitations

**Comment by rob-luke** [comment]
Sorry, don't know how I missed that.

I might move this discussion to ROADMAP where its probably more appropriate too.

**Comment by galenlynch** [comment]
I  have a [package](https://github.com/galenlynch/OpenEphysLoader.jl) for reading [Open Ephys](http://www.open-ephys.org/) files, which I know some people use for EEG acquisition.
